import type { CharacterDefinition } from "../types";

const portrait = (assetKey: string) => `/assets/characters/${assetKey}.png`;

// Live ranking IDs published by the DBGS player tracker. Older releases used
// stable hero-#### reference IDs for fighters that had not appeared in the
// creator's own match history. Keep those canonical IDs for local-setting and
// saved-build compatibility, while resolving both forms here.
export const TRACKER_RANKING_ID_BY_ASSET_KEY: Record<string, string> = {
  character_ssj_goku: "3637745922",
  character_ssj_vegeta: "3354404754",
  character_krillin: "2284137417",
  character_ssj_trunks_teen: "2289211815",
  character_piccolo: "2364114085",
  character_android_18: "3418506376",
  character_majin_buu_good: "4116697413",
  character_zamasu: "2452489494",
  character_gohan_kid: "1788756705",
  character_baby_young_body: "3396651806",
  character_frieza_first_form: "1518901554",
  character_dabura: "3290167663",
  character_cooler_final_form: "2430135778",
  character_super_uub: "2462823744",
  character_bojack_full_power: "3451520862",
  character_ssj2_caulifla: "229525343",
  character_goku_mini: "1258649589",
  character_cell_perfect_form: "3168520270",
  character_android_17: "121489365",
  character_hit: "3267382816",
  character_kale_berserk: "1470876418",
  character_gamma_1_2: "3010125996",
  character_ssj3_goku: "801032716",
  character_ssj_gotenks: "2465666179",
  character_toppo_god: "248776594",
  character_ssj4_vegeta: "2507742314",
  character_ultimate_gohan: "1526300317",
  character_broly: "2735236247",
  character_super_vegito: "649733191",
  character_bardock: "3875954222",
  character_kefla: "1301579830",
  character_ssg_goku: "238912654",
  character_ssg_vegeta: "3892408882",
  character_majin_buu_pure: "1308549053",
  character_frieza_fourth_form: "2497566854",
  character_goku_youth: "1232069625",
  character_bulma_youth: "59260073",
  character_beerus: "581026354",
  character_goku_black: "661292423",
  character_jiren_full_power: "1989055063",
};

export const CHARACTERS: CharacterDefinition[] = [
  {
    rankingId: "3875954222",
    name: "Bardock",
    label: "Ultra Instinct (Sign) Bardock",
    aliases: ["Super Saiyan Bardock", "Bardock", "SSJ Bardock"],
    defaultRole: "tank",
    assetKey: "character_bardock",
    portrait: portrait("character_bardock"),
  },
  {
    rankingId: "hero-0040",
    name: "Jiren (Full Power)",
    label: "Jiren (Full Power)",
    aliases: ["Full Power Jiren", "Jiren"],
    defaultRole: "tank",
    assetKey: "character_jiren_full_power",
    portrait: portrait("character_jiren_full_power"),
  },
  {
    rankingId: "661292423",
    name: "Goku Black",
    label: "Goku Black",
    defaultRole: "technical",
    assetKey: "character_goku_black",
    portrait: portrait("character_goku_black"),
  },
  {
    rankingId: "hero-0038",
    name: "Beerus",
    label: "Beerus",
    defaultRole: "damage",
    assetKey: "character_beerus",
    portrait: portrait("character_beerus"),
  },
  {
    rankingId: "hero-0001",
    name: "Super Saiyan Son Goku",
    label: "Super Saiyan Son Goku",
    aliases: ["Super Saiyan Goku", "SSJ Goku"],
    defaultRole: "damage",
    assetKey: "character_ssj_goku",
    portrait: portrait("character_ssj_goku"),
  },
  {
    rankingId: "hero-0002",
    name: "Super Saiyan Vegeta",
    label: "Super Saiyan Vegeta",
    aliases: ["SSJ Vegeta"],
    defaultRole: "tank",
    assetKey: "character_ssj_vegeta",
    portrait: portrait("character_ssj_vegeta"),
  },
  {
    rankingId: "hero-0003",
    name: "Krillin",
    label: "Krillin",
    defaultRole: "technical",
    assetKey: "character_krillin",
    portrait: portrait("character_krillin"),
  },
  {
    rankingId: "hero-0004",
    name: "Super Saiyan Trunks (Teen)",
    label: "Super Saiyan Trunks (Teen)",
    aliases: ["Super Saiyan Teen Trunks", "SSJ Trunks (Teen)"],
    defaultRole: "damage",
    assetKey: "character_ssj_trunks_teen",
    portrait: portrait("character_ssj_trunks_teen"),
  },
  {
    rankingId: "hero-0005",
    name: "Piccolo",
    label: "Piccolo",
    defaultRole: "damage",
    assetKey: "character_piccolo",
    portrait: portrait("character_piccolo"),
  },
  {
    rankingId: "hero-0006",
    name: "Android 18",
    label: "Android 18",
    aliases: ["Android #18"],
    defaultRole: "damage",
    assetKey: "character_android_18",
    portrait: portrait("character_android_18"),
  },
  {
    rankingId: "hero-0007",
    name: "Majin Buu (Good)",
    label: "Majin Buu (Good)",
    aliases: ["Good Buu", "Fat Buu"],
    defaultRole: "technical",
    assetKey: "character_majin_buu_good",
    portrait: portrait("character_majin_buu_good"),
  },
  {
    rankingId: "hero-0008",
    name: "Zamasu",
    label: "Zamasu",
    defaultRole: "tank",
    assetKey: "character_zamasu",
    portrait: portrait("character_zamasu"),
  },
  {
    rankingId: "hero-0009",
    name: "Son Gohan (Kid)",
    label: "Son Gohan (Kid)",
    aliases: ["Kid Gohan", "Gohan (Kid)"],
    defaultRole: "technical",
    assetKey: "character_gohan_kid",
    portrait: portrait("character_gohan_kid"),
  },
  {
    rankingId: "hero-0010",
    name: "Baby (Young Body)",
    label: "Baby (Young Body)",
    aliases: ["Baby"],
    defaultRole: "tank",
    assetKey: "character_baby_young_body",
    portrait: portrait("character_baby_young_body"),
  },
  {
    rankingId: "hero-0011",
    name: "Frieza (First Form)",
    label: "Frieza (First Form)",
    aliases: ["Freeza (First Form)", "First Form Frieza"],
    defaultRole: "technical",
    assetKey: "character_frieza_first_form",
    portrait: portrait("character_frieza_first_form"),
  },
  {
    rankingId: "hero-0012",
    name: "Dabura",
    label: "Dabura",
    defaultRole: "damage",
    assetKey: "character_dabura",
    portrait: portrait("character_dabura"),
  },
  {
    rankingId: "hero-0013",
    name: "Cooler (Final Form)",
    label: "Cooler (Final Form)",
    aliases: ["Final Form Cooler"],
    defaultRole: "tank",
    assetKey: "character_cooler_final_form",
    portrait: portrait("character_cooler_final_form"),
  },
  {
    rankingId: "hero-0014",
    name: "Super Uub",
    label: "Super Uub",
    aliases: ["Majuub"],
    defaultRole: "damage",
    assetKey: "character_super_uub",
    portrait: portrait("character_super_uub"),
  },
  {
    rankingId: "hero-0015",
    name: "Full Power Bojack",
    label: "Full Power Bojack",
    aliases: ["Bojack (Full Power)", "Bojack"],
    defaultRole: "damage",
    assetKey: "character_bojack_full_power",
    portrait: portrait("character_bojack_full_power"),
  },
  {
    rankingId: "hero-0016",
    name: "Super Saiyan 2 Caulifla",
    label: "Super Saiyan 2 Caulifla",
    aliases: ["SSJ2 Caulifla", "Caulifla"],
    defaultRole: "tank",
    assetKey: "character_ssj2_caulifla",
    portrait: portrait("character_ssj2_caulifla"),
  },
  {
    rankingId: "hero-0017",
    name: "Son Goku (Mini)",
    label: "Son Goku (Mini)",
    aliases: ["Goku (Mini)", "Daima Goku"],
    defaultRole: "damage",
    assetKey: "character_goku_mini",
    portrait: portrait("character_goku_mini"),
  },
  {
    rankingId: "hero-0018",
    name: "Cell (Perfect Form)",
    label: "Cell (Perfect Form)",
    aliases: ["Perfect Cell", "Perfect Form Cell"],
    defaultRole: "tank",
    assetKey: "character_cell_perfect_form",
    portrait: portrait("character_cell_perfect_form"),
  },
  {
    rankingId: "hero-0019",
    name: "Android 17",
    label: "Android 17",
    aliases: ["Android #17"],
    defaultRole: "technical",
    assetKey: "character_android_17",
    portrait: portrait("character_android_17"),
  },
  {
    rankingId: "hero-0020",
    name: "Hit",
    label: "Hit",
    defaultRole: "technical",
    assetKey: "character_hit",
    portrait: portrait("character_hit"),
  },
  {
    rankingId: "hero-0021",
    name: "Super Saiyan Kale (Berserk)",
    label: "Super Saiyan Kale (Berserk)",
    aliases: ["Berserk Kale", "Kale (Berserk)"],
    defaultRole: "damage",
    assetKey: "character_kale_berserk",
    portrait: portrait("character_kale_berserk"),
  },
  {
    rankingId: "hero-0022",
    name: "Gamma 1 & Gamma 2",
    label: "Gamma 1 & Gamma 2",
    aliases: ["Gamma 1 and Gamma 2", "Gamma 1 / Gamma 2"],
    defaultRole: "damage",
    assetKey: "character_gamma_1_2",
    portrait: portrait("character_gamma_1_2"),
  },
  {
    rankingId: "hero-0023",
    name: "Super Saiyan 3 Son Goku",
    label: "Super Saiyan 3 Son Goku",
    aliases: ["Super Saiyan 3 Goku", "SSJ3 Goku"],
    defaultRole: "damage",
    assetKey: "character_ssj3_goku",
    portrait: portrait("character_ssj3_goku"),
  },
  {
    rankingId: "hero-0024",
    name: "Super Saiyan Gotenks",
    label: "Super Saiyan Gotenks",
    aliases: ["SSJ Gotenks", "Gotenks"],
    defaultRole: "technical",
    assetKey: "character_ssj_gotenks",
    portrait: portrait("character_ssj_gotenks"),
  },
  {
    rankingId: "hero-0025",
    name: "God of Destruction Toppo",
    label: "God of Destruction Toppo",
    aliases: ["G.O.D. Toppo", "Toppo"],
    defaultRole: "damage",
    assetKey: "character_toppo_god",
    portrait: portrait("character_toppo_god"),
  },
  {
    rankingId: "2507742314",
    name: "Super Saiyan 4 Vegeta",
    label: "Super Saiyan 4 Vegeta",
    aliases: ["SSJ4 Vegeta"],
    defaultRole: "tank",
    assetKey: "character_ssj4_vegeta",
    portrait: portrait("character_ssj4_vegeta"),
  },
  {
    rankingId: "hero-0027",
    name: "Ultimate Gohan",
    label: "Ultimate Gohan",
    aliases: ["Mystic Gohan"],
    defaultRole: "technical",
    assetKey: "character_ultimate_gohan",
    portrait: portrait("character_ultimate_gohan"),
  },
  {
    rankingId: "2735236247",
    name: "Broly",
    label: "Legendary Super Saiyan Broly",
    aliases: ["Legendary Super Saiyan Broly", "LSSJ Broly"],
    defaultRole: "damage",
    assetKey: "character_broly",
    portrait: portrait("character_broly"),
  },
  {
    rankingId: "hero-0029",
    name: "Super Vegito",
    label: "Super Vegito",
    aliases: ["Vegito"],
    defaultRole: "damage",
    assetKey: "character_super_vegito",
    portrait: portrait("character_super_vegito"),
  },
  {
    rankingId: "1301579830",
    name: "Kefla",
    label: "Super Saiyan 2 Kefla",
    aliases: ["Super Saiyan 2 Kefla", "SSJ2 Kefla"],
    defaultRole: "damage",
    assetKey: "character_kefla",
    portrait: portrait("character_kefla"),
  },
  {
    rankingId: "hero-0032",
    name: "Super Saiyan God Son Goku",
    label: "Super Saiyan God Son Goku",
    aliases: ["Super Saiyan God Goku", "SSG Goku"],
    defaultRole: "damage",
    assetKey: "character_ssg_goku",
    portrait: portrait("character_ssg_goku"),
  },
  {
    rankingId: "hero-0033",
    name: "Super Saiyan God Vegeta",
    label: "Super Saiyan God Vegeta",
    aliases: ["SSG Vegeta"],
    defaultRole: "tank",
    assetKey: "character_ssg_vegeta",
    portrait: portrait("character_ssg_vegeta"),
  },
  {
    rankingId: "hero-0034",
    name: "Majin Buu (Pure)",
    label: "Majin Buu (Pure)",
    aliases: ["Pure Majin Buu", "Kid Buu"],
    defaultRole: "technical",
    assetKey: "character_majin_buu_pure",
    portrait: portrait("character_majin_buu_pure"),
  },
  {
    rankingId: "hero-0035",
    name: "Frieza (Fourth Form)",
    label: "Frieza (Fourth Form)",
    aliases: ["Freeza (Fourth Form)", "Final Form Frieza"],
    defaultRole: "technical",
    assetKey: "character_frieza_fourth_form",
    portrait: portrait("character_frieza_fourth_form"),
  },
  {
    rankingId: "1232069625",
    name: "Son Goku (Youth)",
    label: "Son Goku (Youth)",
    aliases: ["Goku (Youth)", "Youth Goku", "Kid Goku"],
    defaultRole: "damage",
    assetKey: "character_goku_youth",
    portrait: portrait("character_goku_youth"),
  },
  {
    rankingId: "hero-0037",
    name: "Bulma (Youth)",
    label: "Bulma (Youth)",
    aliases: ["Youth Bulma", "Bulma"],
    defaultRole: "tank",
    assetKey: "character_bulma_youth",
    portrait: portrait("character_bulma_youth"),
  },
];

function normalizeCharacterName(value: string): string {
  return value
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/&/g, " and ")
    .replace(/[^a-z0-9]+/g, " ")
    .trim()
    .replace(/\s+/g, " ");
}

export function getCharacter(rankingId: string, trackerName?: string): CharacterDefinition {
  const byId = CHARACTERS.find((character) => character.rankingId === rankingId
    || (character.assetKey && TRACKER_RANKING_ID_BY_ASSET_KEY[character.assetKey] === rankingId));
  if (byId) return byId;

  const normalizedName = normalizeCharacterName(trackerName ?? "");
  if (normalizedName) {
    const byName = CHARACTERS.find((character) =>
      [character.name, character.label, ...(character.aliases ?? [])]
        .some((candidate) => normalizeCharacterName(candidate) === normalizedName),
    );
    if (byName) return byName;
  }

  const fallbackName = trackerName?.trim() || "Unknown Fighter";
  return {
    rankingId,
    name: fallbackName,
    label: fallbackName,
    defaultRole: "damage",
  };
}
